export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	SET_CLASSIC_BOOKS: 'SET_CLASSIC_BOOKS',
	API_LOADING_CLASSIC_BOOKS: 'API_LOADING_CLASSIC_BOOKS',

	SET_PROGRAMMING_BOOKS: 'SET_PROGRAMMING_BOOKS',
	API_LOADING_PROGRAMMING_BOOKS: 'API_LOADING_PROGRAMMING_BOOKS',

	SET_DESIGN_BOOKS: 'SET_DESIGN_BOOKS',
	API_LOADING_DESIGN_BOOKS: 'API_LOADING_DESIGN_BOOKS',

};
