/* eslint-disable @typescript-eslint/no-explicit-any */
import { Dispatches } from '@constant';
import { BooksInterface } from '@interfaces';

const DATA_DUMMY = {
	'key': '/subjects/kids',
	'name': 'kids',
	'subject_type': 'subject',
	'work_count': 147,
	'works': [
		{
			'key': '/works/OL29983W',
			'title': 'Little Women',
			'edition_count': 1547,
			'cover_id': 6795866,
			'cover_edition_key': 'OL24620928M',
			'subject': [
				'Romans',
				'Jeunes filles',
				'Soeurs',
				'Sisters',
				'Young women',
				'Fiction',
				'Fiction, women',
				'Young women, fiction',
				'Family life',
				'Literatura Norte Americana',
				'Families',
				'Juvenile fiction',
				'March family (Fictitious characters)',
				'Domestic fiction',
				'Bildungsromans',
				'Historical fiction',
				'Children\'s fiction',
				'Family life, fiction',
				'Sisters, fiction',
				'New england, fiction',
				'March family (fictitious characters), fiction',
				'American fiction (fictional works by one author)',
				'Fiction, family life, general',
				'Mothers and daughters, fiction',
				'History',
				'Dictionaries',
				'English language',
				'Spanish',
				'Familias',
				'Hermanas',
				'Madre e hijas',
				'Mothers and daughters',
				'Ficción',
				'Young men',
				'Social life and customs',
				'Large type books',
				'Manners and customs',
				'Fiction, coming of age',
				'Family, fiction',
				'Fiction, family life',
				'Children: Grades 4-6',
				'Family',
				'Protected DAISY',
				'Accessible book',
				'Fiction, general',
				'Coloring books',
				'German',
				'Literarne študije',
				'Little women""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""',
				'Japanese language books',
				'New England',
				'Novela estadounidense',
				'Američki građanski rat',
				'ljubav',
				'obitelj',
				'odrastanje',
				'growing up',
				'žene',
				'New England in fiction',
				'Sisters in fiction',
				'Family life in fiction',
				'Mothers and daughters in fiction',
				'Young women in fiction',
				'Family in fiction',
				'Literature, collections',
				'American literature',
				'New England -- Fiction',
				'March family (Fictitious characters) -- Fiction',
				'Sisters -- Fiction',
				'Family life -- New England -- Fiction',
				'Mothers and daughters -- Fiction',
				'Young women -- Fiction',
				'Autobiographical fiction',
				'Children',
				'Children\'s',
				'Kids',
				'Juvenile',
				'American',
				'Classic',
				'Literature',
				'Historical',
				'Mothers',
				'Daughtes',
				'Married women',
				'Orphans',
				'Coming of life',
				'Manners',
				'Customs',
				'Conduct of life',
				'Social life',
				'open_syllabus_project',
				'Mother-daughter relationship',
				'Folklore',
				'Reading Level-Grade 5',
				'Reading Level-Grade 4',
				'Reading Level-Grade 7',
				'Reading Level-Grade 6',
				'Reading Level-Grade 8',
				'Fiction, biographical',
				'Buried treasure',
				'Pirates',
				'Adventure and adventurers',
				'Robin Hood (Legendary character)',
				'Legends',
				'English Adventure stories',
				'Jungle animals',
				'Feral children',
				'Jungles',
				'Animals',
				'Short stories',
				'Adaptations',
				'Fiction, historical, general',
				'Fiction, romance, general',
				'Chang pian xiao shuo',
				'Zhang pian xiao shuo',
				'AR 8.6.',
				'Animals, fiction',
				'Friendship, fiction',
				'England, fiction',
				'Treasure island (imaginary place), fiction',
				'British and irish fiction (fictional works by one author)',
				'Coming of age',
				'Spanish language materials',
				'Famille March (Personnages fictifs)',
				'Romans, nouvelles, etc. pour la jeunesse',
				'Mères et filles',
				'Jeunes femmes',
				'Sœurs',
				'Familles',
				'Madres e hijas',
				'Novela juvenil',
				'Jóvenes (Mujeres)',
				'Materiales en español',
				'Novela',
				'FICTION / Classics',
				'Hermanos',
				'Familia',
				'Little women (Alcott, Louisa May)',
			],
			'ia_collection': [
				'additional_collections',
				'americana',
				'aozorabunko',
				'bpljordan-ol',
				'cdl',
				'china',
				'cnusd-ol',
				'delawarecountydistrictlibrary',
				'delawarecountydistrictlibrary-ol',
				'framingham-ol',
				'goffstownlibrary-ol',
				'gwulibraries-ol',
				'iacl',
				'inlibrary',
				'internetarchivebooks',
				'juvenilehistoricalcollection',
				'kalamazoocollege-ol',
				'library_of_atlantis',
				'librarygenesis',
				'marygrovecollege',
				'marymount-ol',
				'microfilm',
				'newyorkpubliclibrary',
				'openlibrary-d-ol',
				'popularchinesebooks',
				'pratt',
				'printdisabled',
				'rbcgen',
				'spokanepubliclibrary-ol',
				'stmaryscountylibrary',
				'toronto',
				'trent_university',
				'tulsacc-ol',
				'unb-ol',
				'unclibraries',
				'university_of_alberta_libraries',
				'university_of_alberta_libraries_microfilm',
				'university_of_illinois_urbana-champaign',
				'universityofcoloradoboulder-ol',
				'universityofoklahoma-ol',
				'universityofthewest-ol',
				'uslprototype',
				'worthingtonlibraries-ol',
				'yrlsc',
			],
			'lendinglibrary': false,
			'printdisabled': true,
			'lending_edition': 'OL7060579M',
			'lending_identifier': 'littlewomenormeg00alcoiala',
			'authors': [
				{
					'key': '/authors/OL26680A',
					'name': 'Louisa May Alcott',
				},
			],
			'first_publish_year': 1848,
			'ia': 'littlewomenormeg00alcoiala',
			'public_scan': true,
			'has_fulltext': true,
			'availability': {
				'status': 'open',
				'available_to_browse': false,
				'available_to_borrow': false,
				'available_to_waitlist': false,
				'is_printdisabled': false,
				'is_readable': true,
				'is_lendable': false,
				'is_previewable': true,
				'identifier': 'littlewomenormeg00alcoiala',
				'isbn': null,
				'oclc': null,
				'openlibrary_work': 'OL29983W',
				'openlibrary_edition': 'OL7060579M',
				'last_loan_date': null,
				'num_waitlist': null,
				'last_waitlist_date': null,
				'is_restricted': false,
				'is_browseable': false,
				'__src__': 'core.models.lending.get_availability',
			},
		},
		{
			'key': '/works/OL82586W',
			'title': 'Harry Potter and the Deathly Hallows',
			'edition_count': 115,
			'cover_id': 10110415,
			'cover_edition_key': 'OL28172760M',
			'subject': [
				'the Elder Wand',
				'children\'s books',
				'dementors',
				'good and evil',
				'Juvenile literature',
				'Juvenile works',
				'Death',
				'Fiction',
				'Wizards',
				'New York Times bestseller',
				'nyt:series_books=2006-09-16',
				'Schools',
				'Magic',
				'Magia',
				'Ficción juvenil',
				'Novela fantástica',
				'Magos',
				'Escuelas',
				'Juvenile fiction',
				'dark magic',
				'Coming of age',
				'heroics',
				'fantasy',
				'action',
				'adventure',
				'orphans',
				'foster homes',
				'young adult',
				'children',
				'children\'s literature',
				'boarding school',
				'wizardry',
				'mystery',
				'kids',
				'witchcraft',
				'war',
				'Magie',
				'Magiciens',
				'Roman pour la jeunesse',
				'Mort',
				'Sorcellerie',
				'Romans, nouvelles, etc. pour la jeunesse',
				'Internats',
				'Fantasy fiction',
				'Roman fantastique',
				'Ecoles',
				'Boarding schools',
				'Sorciers',
				'Hogwarts School of Witchcraft and Wizardry (Imaginary place) -- Juvenile fiction',
				'Hogwarts School of Witchcraft and Wizardry (Imaginary place)',
				'Harry Potter (Fictitious character)',
				'Potter, Harry (Fictitious character) -- Juvenile fiction',
				'Wizards -- Fiction',
				'Magic -- Fiction',
				'Schools -- Fiction',
				'Magos -- Ficción juvenil',
				'Magia -- Ficción juvenil',
				'Escuelas -- Ficción juvenil',
				'England -- Fiction',
				'Inglaterra -- Ficción juvenil',
				'Hermione Granger (Fictitious character)',
				'Hogwarts School of Witchcraft and Wizardry (Imaginary organization)',
				'Ron Weasley (Fictitious character)',
				'School stories',
				'Family',
				'Orphans & Foster Homes',
				'Social Themes',
				'Fantasy & Magic',
				'Fictional Works',
				'Bildungsromans',
				'Witches',
				'Friendship',
				'Reading Level-Grade 9',
				'Reading Level-Grade 11',
				'Reading Level-Grade 10',
				'Reading Level-Grade 12',
				'Potter, harry (fictitious character), fiction',
				'Wizards, fiction',
				'Hogwarts school of witchcraft and wizardry (imaginary organization), fiction',
				'England, fiction',
				'Schools, fiction',
				'Magic, fiction',
				'Children\'s fiction',
				'English literature',
				'Fiction, fantasy, general',
				'Méchanceté',
				'Quête (Littérature)',
				'Potter, Harry (Personnage fictif)',
				'Large type books',
				'New York Times reviewed',
				'Poudlard (Organisation imaginaire)',
				'Écoles',
				'Illusion (performing art)',
				'Schools (institutions)',
				'Schools (buildings)',
				'Child and youth fiction',
			],
			'ia_collection': [
				'americana',
				'americanuniversity-ol',
				'bannedbooks',
				'barryuniversity-ol',
				'belmont-ol',
				'bostonuniversitylibraries-ol',
				'bpljordan-ol',
				'china',
				'cnusd-ol',
				'cua-ol',
				'dartmouthlibrary-ol',
				'delawarecountydistrictlibrary',
				'delawarecountydistrictlibrary-ol',
				'denverpubliclibrary-ol',
				'drakeuniversity-ol',
				'framingham-ol',
				'goffstownlibrary-ol',
				'gwulibraries-ol',
				'inlibrary',
				'internetarchivebooks',
				'ithacacollege-ol',
				'johnshopkins-ol',
				'librarygenesis',
				'marygrovecollege',
				'marymount-ol',
				'occidentalcollegelibrary-ol',
				'openlibrary-d-ol',
				'popularchinesebooks',
				'printdisabled',
				'rochester-ol',
				'salisburyfreelibrary-ol',
				'spokanepubliclibrary-ol',
				'the-claremont-colleges-ol',
				'tulsacc-ol',
				'uhmauicollege-ol',
				'unb-ol',
				'uni-ol',
				'universityofarizona-ol',
				'universityofcoloradoboulder-ol',
				'universityofoklahoma-ol',
				'universityofthewest-ol',
				'wilsoncollege-ol',
				'worthingtonlibraries-ol',
			],
			'lendinglibrary': false,
			'printdisabled': true,
			'lending_edition': 'OL27119406M',
			'lending_identifier': 'haliboteyusiwang0007rowl',
			'authors': [
				{
					'key': '/authors/OL23919A',
					'name': 'J. K. Rowling',
				},
			],
			'first_publish_year': 2007,
			'ia': 'haliboteyusiwang0007rowl',
			'public_scan': false,
			'has_fulltext': true,
			'availability': {
				'status': 'borrow_available',
				'available_to_browse': true,
				'available_to_borrow': false,
				'available_to_waitlist': false,
				'is_printdisabled': true,
				'is_readable': false,
				'is_lendable': true,
				'is_previewable': true,
				'identifier': 'haliboteyusiwang0007rowl',
				'isbn': '9787020063659',
				'oclc': null,
				'openlibrary_work': 'OL82586W',
				'openlibrary_edition': 'OL27119406M',
				'last_loan_date': null,
				'num_waitlist': null,
				'last_waitlist_date': null,
				'is_restricted': true,
				'is_browseable': true,
				'__src__': 'core.models.lending.get_availability',
			},
		},
		{
			'key': '/works/OL15854658W',
			'title': 'Black Beauty',
			'edition_count': 107,
			'cover_id': 5007492,
			'cover_edition_key': 'OL9730766M',
			'subject': [
				'Black Beauty',
				'Anna Sewell',
				'Original publication 1877',
				'19th Century',
				'Children',
				'Children\'s',
				'Kids',
				'Juvenile',
				'Classic',
				'Fiction',
				'Books',
				'Stories',
				'Drama',
				'Biography',
				'History',
				'Legends',
				'Animals',
				'Classic Literature',
				'Juvenile Literature',
				'Animals - Horses',
				'Horses',
				'Animal rights',
				'Humane treatment',
				'Kindness',
				'Gentleness',
				'Goodness & cruelty',
				'Morals',
				'Morality',
				'Children\'s fiction',
				'Horses, fiction',
				'England, fiction',
				'Animals, treatment, fiction',
				'Juvenile fiction',
				'Folklore',
				'Specimens',
				'Toy and movable books',
				'Juvenile sound recordings',
				'Black Beauty (Fictitious character)',
				'High interest-low vocabulary books',
				'Easy reading materials',
				'Child and youth fiction',
				'Fiction, historical',
				'Great britain, fiction',
				'Readers',
				'Fairy tales',
				'Adventure and adventurers, fiction',
				'Fiction, romance, general',
				'Adaptations',
				'Comic books, strips',
				'Graphic novels',
				'Animal welfare',
				'Social conditions',
				'Treatment',
				'Literature and fiction, juvenile',
				'Chevaux',
				'Romans, nouvelles, etc. pour la jeunesse',
				'New england, fiction',
			],
			'ia_collection': [
				'americana',
				'barryuniversity-ol',
				'blc',
				'bostonuniversitylibraries-ol',
				'bpljordan-ol',
				'brynmawr-ol',
				'cdl',
				'china',
				'cnusd-ol',
				'delawarecountydistrictlibrary',
				'iacl',
				'inlibrary',
				'internetarchivebooks',
				'library_of_atlantis',
				'openlibrary-d-ol',
				'printdisabled',
				'stmaryscountylibrary',
				'unb-ol',
				'websterfamilyvetmed',
				'yrlsc',
			],
			'lendinglibrary': false,
			'printdisabled': true,
			'lending_edition': 'OL7242604M',
			'lending_identifier': 'blackbeautyhisgr00seweiala',
			'authors': [
				{
					'key': '/authors/OL25123A',
					'name': 'Anna Sewell',
				},
			],
			'first_publish_year': 1877,
			'ia': 'blackbeautyhisgr00seweiala',
			'public_scan': true,
			'has_fulltext': true,
			'availability': {
				'status': 'open',
				'available_to_browse': false,
				'available_to_borrow': false,
				'available_to_waitlist': false,
				'is_printdisabled': false,
				'is_readable': true,
				'is_lendable': false,
				'is_previewable': true,
				'identifier': 'blackbeautyhisgr00seweiala',
				'isbn': null,
				'oclc': null,
				'openlibrary_work': 'OL40252W',
				'openlibrary_edition': 'OL7242604M',
				'last_loan_date': null,
				'num_waitlist': null,
				'last_waitlist_date': null,
				'is_restricted': false,
				'is_browseable': false,
				'__src__': 'core.models.lending.get_availability',
			},
		},
		{
			'key': '/works/OL15049633W',
			'title': 'La Petite Sirene (French Well Loved Tales)',
			'edition_count': 54,
			'cover_id': 10563313,
			'cover_edition_key': 'OL10535620M',
			'subject': [
				'Contes danois',
				'Fairy tales',
				'Mermaids',
				'Fiction',
				'Children\'s stories, Danish',
				'Translations into English',
				'Coloring books',
				'Translations into Russian',
				'Children\'s audiobooks',
				'Translations into Marathi',
				'Fairytales',
				'Juvenile fiction',
				'Tales',
				'Plays',
				'Children\'s plays',
				'Children\'s fiction',
				'Mermaids, fiction',
				'Children\'s stories, English',
				'Musical books',
				'Sound effects books',
				'Specimens',
				'Picture puzzles',
				'Toy and movable books',
				'Picture books',
				'Hans Christian Anderson (1805-1875)',
				'Easy reading',
				'Kids',
				'Children',
				'Children\'s',
				'Juvenile',
				'Books',
				'Picture Books',
				'Stories',
				'Folklore',
				'Fables',
				'Fantasy',
				'Contes de fées',
				'Literature and fiction, juvenile',
				'Postcards, juvenile literature',
				'Folklore, denmark',
			],
			'ia_collection': [
				'bpljordan-ol',
				'china',
				'cnusd-ol',
				'denverpubliclibrary-ol',
				'framingham-ol',
				'inlibrary',
				'internetarchivebooks',
				'printdisabled',
				'stmaryscountylibrary',
				'unb-ol',
				'uni-ol',
				'universityofoklahoma-ol',
			],
			'lendinglibrary': false,
			'printdisabled': true,
			'lending_edition': 'OL5317871M',
			'lending_identifier': 'hanschristianand0000ande_k4s1',
			'authors': [
				{
					'key': '/authors/OL25931A',
					'name': 'Hans Christian Andersen',
				},
				{
					'key': '/authors/OL7597674A',
					'name': 'Yayoi Kusama',
				},
				{
					'key': '/authors/OL6981084A',
					'name': 'Bernadette Watts',
				},
			],
			'first_publish_year': 1935,
			'ia': 'hanschristianand0000ande_k4s1',
			'public_scan': false,
			'has_fulltext': true,
			'availability': {
				'status': 'borrow_available',
				'available_to_browse': true,
				'available_to_borrow': true,
				'available_to_waitlist': false,
				'is_printdisabled': true,
				'is_readable': false,
				'is_lendable': true,
				'is_previewable': true,
				'identifier': 'hanschristianand0000ande_k4s1',
				'isbn': '006023783X',
				'oclc': null,
				'openlibrary_work': 'OL25528W',
				'openlibrary_edition': 'OL5317871M',
				'last_loan_date': '2020-07-30T14:32:00Z',
				'num_waitlist': '0',
				'last_waitlist_date': null,
				'is_restricted': true,
				'is_browseable': true,
				'__src__': 'core.models.lending.get_availability',
			},
		},
	],
};

const initialState: BooksInterface.BooksState = {
	loadingClassicBooks: false,
	loadingProgrammingBooks: false,
	loadingDesignBooks: false,
	classicBooks: DATA_DUMMY,
	programmingBooks: DATA_DUMMY,
	designBooks: DATA_DUMMY,
};

type Actions = { type: string; payload: any };

const miscReducers = (
	state = initialState,
	action: Actions,
): BooksInterface.BooksState => {
	const { type, payload } = action;
	switch (type) {
		case Dispatches.API_LOADING_CLASSIC_BOOKS:
			return {
				...state,
				loadingClassicBooks: payload,
			};
		case Dispatches.SET_CLASSIC_BOOKS:
			let newData = payload.response;
			if (payload.offset > 0) {
				const oldData = state.classicBooks;
				newData = {
					...oldData,
					works: oldData.works?.concat(payload.response.works),
				};
			}
			return {
				...state,
				classicBooks: newData,
			};
		case Dispatches.API_LOADING_PROGRAMMING_BOOKS:
			return {
				...state,
				loadingProgrammingBooks: payload,
			};
		case Dispatches.SET_PROGRAMMING_BOOKS:
			let newDataProgramming = payload.response;
			if (payload.offset > 0) {
				const oldData = state.programmingBooks;
				newDataProgramming = {
					...oldData,
					works: oldData.works?.concat(payload.response.works),
				};
			}
			return {
				...state,
				programmingBooks: newDataProgramming,
			};
		case Dispatches.API_LOADING_DESIGN_BOOKS:
			return {
				...state,
				loadingDesignBooks: payload,
			};
		case Dispatches.SET_DESIGN_BOOKS:
			let newDataDesign = payload.response;
			if (payload.offset > 0) {
				const oldData = state.designBooks;
				newDataDesign = {
					...oldData,
					works: oldData.works?.concat(payload.response.works),
				};
			}
			return {
				...state,
				designBooks: newDataDesign,
			};
		default:
			return state;
	}
};

export default miscReducers;
